name: stocksense
description: StockSense Trading App
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^17.2.2
  http: ^1.2.1
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
dependency_overrides:
  flutter_background_service_android: ^6.3.1
