const String APP_VERSION = 'V1.0.1';
const String BUILD_DATE = '02 Jul 2026 10:15';
const String SERVER_URL = 'https://stock-sense-server--rvignesh061999.replit.app/api';
const List<String> ALL_STOCKS = [
  'HDFCBANK','ICICIBANK','KOTAKBANK','AXISBANK','SBIN','BANKBARODA','PNB','INDUSINDBK','YESBANK','FEDERALBNK',
  'CANBK','BAJFINANCE','BAJAJFINSV','MUTHOOTFIN','LICHSGFIN','LICI','SBILIFE','HDFCLIFE',
  'TCS','INFY','WIPRO','HCLTECH','TECHM','LTIM','TATACOMM','MPHASIS','PERSISTENT',
  'RELIANCE','ONGC','IOC','BPCL','COALINDIA','BHARTIARTL','IDEA',
  'TATAMOTORS','MARUTI','BAJAJ-AUTO','EICHERMOT','HEROMOTOCO','TVSMOTOR',
  'TATASTEEL','JSWSTEEL','HINDALCO','VEDL','SAIL',
  'NTPC','POWERGRID','TATAPOWER','ADANIPOWER','TORNTPOWER',
  'ADANIGREEN','RPOWER','SUZLON','IREDA',
  'BEL','BHEL','BEML','HAL','GRSE','MAZDOCK','COCHINSHIP','HBLENGINE',
  'LT','NBCC','HUDCO','ADANIPORTS','ADANIENT','IRFC','RVNL',
  'SUNPHARMA','DRREDDY','CIPLA','APOLLOHOSP','DIVISLAB','BIOCON','AUROPHARMA',
  'ITC','HINDUNILVR','NESTLEIND','BRITANNIA','DABUR','MARICO',
  'ASIANPAINT','TITAN','HAVELLS','VOLTAS','DIXON',
  'ZOMATO','IRCTC','NYKAA','PAYTM','SWIGGY',
];
const int MARKET_OPEN_HOUR=9,MARKET_OPEN_MIN=15;
const int MARKET_CLOSE_HOUR=15,MARKET_CLOSE_MIN=30;
const int BEST_ENTRY_HOUR=10,BEST_ENTRY_MIN=0;
const int EXIT_WARNING_HOUR=11,EXIT_WARNING_MIN=30;
// 2026-07-08: exact matches to the web app's :root CSS variables
// (--bg, --s1, --b1, --b2, --green, --red, --yellow, --blue, --text, --muted)
// so new screens (Admin/Kibana, Timer Log) look like the web app, not ClaudeLink.
const int COLOR_GREEN=0xFF00FF88,COLOR_RED=0xFFFF3355;
const int COLOR_YELLOW=0xFFFFBB00,COLOR_BLUE=0xFF3D9BFF;
const int COLOR_BG=0xFF07080A,COLOR_CARD=0xFF0D0F12,COLOR_CARD2=0xFF131618;
const int COLOR_BORDER=0xFF1F2228,COLOR_BORDER2=0xFF2A2F38;
const int COLOR_TEXT=0xFFE8EAF0,COLOR_MUTED=0xFF525870;
const int NOTIF_SCAN_PROGRESS=1,NOTIF_SCAN_COMPLETE=2,NOTIF_REST_TIMER=3;
