const String APP_VERSION = 'V1.0.0';
const String SERVER_URL = 'https://stock-sense-server--rvignesh061999.replit.app/api';
const List<String> ALL_STOCKS = [
  'HDFCBANK','ICICIBANK','KOTAKBANK','AXISBANK','SBIN','BANKBARODA','PNB','INDUSINDBK','YESBANK','FEDERALBNK',
  'CANBK','BAJFINANCE','BAJAJFINSV','MUTHOOTFIN','LICHSGFIN','LICI','SBILIFE','HDFCLIFE',
  'TCS','INFY','WIPRO','HCLTECH','TECHM','LTIM','TATACOMM','MPHASIS','PERSISTENT',
  'RELIANCE','ONGC','IOC','BPCL','COALINDIA','BHARTIARTL','IDEA',
  'TATAMOTORS','MARUTI','BAJAJ-AUTO','EICHERMOT','HEROMOTOCO','TVSMOTOR',
  'TATASTEEL','JSWSTEEL','HINDALCO','VEDL','SAIL',
  'NTPC','POWERGRID','TATAPOWER','ADANIPOWER','TORNTPOWER',
  'ADANIGREEN','RPOWER','SUZLON','IREDA',
  'BEL','BHEL','BEML','HAL','GRSE','MAZDOCK','COCHINSHIP','HBLENGINE',
  'LT','NBCC','HUDCO','ADANIPORTS','ADANIENT','IRFC','RVNL',
  'SUNPHARMA','DRREDDY','CIPLA','APOLLOHOSP','DIVISLAB','BIOCON','AUROPHARMA',
  'ITC','HINDUNILVR','NESTLEIND','BRITANNIA','DABUR','MARICO',
  'ASIANPAINT','TITAN','HAVELLS','VOLTAS','DIXON',
  'ZOMATO','IRCTC','NYKAA','PAYTM','SWIGGY',
];
const int MARKET_OPEN_HOUR=9,MARKET_OPEN_MIN=15;
const int MARKET_CLOSE_HOUR=15,MARKET_CLOSE_MIN=30;
const int BEST_ENTRY_HOUR=10,BEST_ENTRY_MIN=0;
const int EXIT_WARNING_HOUR=11,EXIT_WARNING_MIN=30;
const int COLOR_GREEN=0xFF00FF88,COLOR_RED=0xFFFF4444;
const int COLOR_YELLOW=0xFFFFAA00,COLOR_BG=0xFF0A0A0A,COLOR_CARD=0xFF111111;
const int NOTIF_SCAN_PROGRESS=1,NOTIF_SCAN_COMPLETE=2,NOTIF_REST_TIMER=3;
